const NavList = [
    {
        "id":1,
        "title":"首页",
        "path":"/admin/home",
        "type":"home"
    },
    {
        "id":2,
        "title":"用户信息",
        "type":"user",
        "children":[
            {
                "id":21,
                "title":"用户列表",
                "path":"/admin/userList",
                "type":"user"
            },
            {
                "id":22,
                "title":"用户统计",
                "path":"/admin/userInfo",
                "type":"user"
            }
        ]
    },
    {
        "id":3,
        "title":"商品信息",
        "type":"shop",
        "children":[
            {
                "id":31,
                "title":"商品列表",
                "path":"/admin/goodsList",
                "type":"shop"
            },
            {
                "id":32,
                "title":"商品统计",
                "path":"/admin/goodsInfo",
                "type":"shop"
            }
        ]
    },
    {
        "id":4,
        "title":"相册",
        "path":"/admin/photo",
        "type":"camera"
    },
    {
        "id":5,
        "title":"权限管理",
        "path":"/admin/setting",
        "type":"setting"
    }
]

export default NavList;